version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CACHE_HOST=redis
      - CACHE_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - SERVER_HEALTH_CHECK_ENDPOINT=${SERVER_HEALTH_CHECK_ENDPOINT}
      - SERVER_PORT=${SERVER_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - ENCODED_CERT=${ENCODED_CERT}
      - CACHE_ENABLE_TLS=${CACHE_ENABLE_TLS}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6385:${CACHE_PORT}"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "${DB_PORT}:${DB_PORT}"
